### PR TITLE
add missing option

### PR DESCRIPTION
**Pull request by ndenev**
This seems to have been missed before, and calls without it are failing.

### CODE REVIEW

**Comment by robison** [comment]
Just out of curiosity, what version is this running against? In 10.1, it appears that the 'vserver' path is fully deprecated.

``` Python
>>> import nsnitro
from nsnitro import *
>>> from nsnitro import *
>>> n = NSNitro('10.216.91.222', 'nsroot', 'nsroot', useSSL=False)
>>> n.login()
{u'errorcode': 0, u'message': u'Done', u'sessionid': u'##0203D370A0FD6702D7EDF5166445EC935183F96E2ADDB24AF1C4E215A72C', u'severity': u'NONE'}
>>> n.NSVServer.get_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: NSNitro instance has no attribute 'NSVServer'
>>> NSVServer.get_all(n)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nsnitro/nsresources/nsvserver.py", line 565, in get_all
    __json_vservers = nitro.get(__url).get_response_field(NSVServer.get_resourcetype())
  File "nsnitro/nsnitro.py", line 106, in get
    NSNitroResponse(e.read())
  File "nsnitro/nsutil.py", line 21, in __init__
    self.__parse_response()
  File "nsnitro/nsutil.py", line 35, in __parse_response
    self._raise_exception()
  File "nsnitro/nsutil.py", line 51, in _raise_exception
    raise exception_class(self.message, self.errorcode)
nsnitro.nsexceptions.nsexceptions.NSNitroNserrNosuchcmd: u'No such command [vserver]'

```

**Comment by favoretti** [comment]
We have it running against 9.3 and from what I understand somewhere against 10.1 build 123.9. They've confirmed basic functionality working, although I haven't tested it myself yet.

**Comment by robison** [comment]
For the 'vserver' path/functionality? Doesn't seem to work on NSVPX 10.1 build 124.13. Hmm. I might be missing something; licensing or the like.

**Comment by favoretti** [comment]
Yep, also for the vservers.. But now I'm selling you something I've just heard, but never confirmed.
I'll try to make some time in the coming weeks to validate.
